# name: My First Workflow
run-name: workflow run by @${{ github.actor }}

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: [event1, event2]

  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        # type: environment
        required: true

jobs:
  NewJob:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - run: |
          echo "Homedrive: ${{ inputs.homedrive }}"
          echo "Log level: ${{ inputs.logLevel }}"
          echo "Tag source: ${{ inputs.tag }}"
          echo "Environment ${{ inputs.environment }}"
        name: Workflow Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - run: |
          echo "Payload: ${{ toJSON(github.event.client_payload) }}"
        name: Payload
        if: ${{ github.event_name == 'repository_dispatch' }}

      - run: echo "👋 Hi there!"

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=green" >> "$GITHUB_ENV"

      - run: |
          echo "${{ env.action_state }}" # This will output 'green'

      - name: Checkout
        uses: actions/checkout@v4

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

      - run: |
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "The runner's operating system is $RUNNER_OS"

      - run: echo '### Hi there! :rocket:' >> $GITHUB_STEP_SUMMARY
      - run: echo '### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
      - run: echo '<h2>Great feature!</h2>' >> $GITHUB_STEP_SUMMARY

