run-name: workflow run by @${{ github.actor }}

# on:
#   push:
on:
  push:
    branches:
      # - main
      - foobarbaz

jobs:
  create-new-issue:
    permissions:
      issues: write
    strategy:
      matrix:
        prod: [prod1, prod2]
        level: [dev, stage, prod]
    uses: ./.github/workflows/create-failure-issue.yml
    secrets: inherit
    with:
      title: "${{ matrix.prod}} issue"
      body: "Update for ${{ matrix.level }}"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      # - run: echo ${{ needs.create-new-issue.outputs.issue-num }}
      - run: echo ${{ needs.create-new-issue.outputs.inum }}
